version: '3'
services: 
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins_master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home=/var/jenkins_home
    # envirnoment:
    # depends_on:
  agent1:
    image: jenkins/inbound-agent
    container_name: agent1
    # ports:
    # volumes:
    envirnoment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_SECRET=
      - JENKINS_AGENT_NAME=agent1
    depends_on:
      - jenkins
  agent2:
    image: jenkins/inbound-agent
    container_name: agent2
    # ports:
    # volumes:
    envirnoment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_SECRET=
      - JENKINS_AGENT_NAME=agent2
    depends_on:
      - jenkins
volumes:
  jenkins_home:
